# Generated by Django 3.0.6 on 2020-05-19 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_name', models.CharField(max_length=20)),
                ('word_sound', models.FileField(upload_to='word_sounds')),
                ('vowel_number', models.IntegerField()),
                ('vowel_name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_username', models.CharField(default='Guest', max_length=100)),
                ('quiz_number_of_word', models.IntegerField()),
                ('quiz_sounds', models.CharField(max_length=100)),
                ('quiz_number_of_gusses', models.IntegerField()),
                ('quiz_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('quiz_number_of_questions', models.IntegerField(default=10)),
                ('quiz_number_of_current_question', models.IntegerField(default=1)),
                ('quiz_score', models.IntegerField(default=0)),
                ('quiz_questions', models.ManyToManyField(to='questions.Question')),
            ],
        ),
    ]
