# Generated by Django 3.0.6 on 2020-05-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_score_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
